version: '3'
services:
  app:
    image: dreamjobs
    command: bash -c
            'bundle exec rails s -p 3000 -b "0.0.0.0"'
    volumes:
      - .:/dreamjobs
    depends_on:
      - postgres
    ports:
      - 3000:3000
    tty: true
    stdin_open: true

  postgres:
    image: postgres:10.5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
