default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: postgres
  username: postgres

development:
  <<: *default
  database: dreamjobs_development
test:
  <<: *default
  database: dreamjobs_test
production:
  <<: *default
  database: dreamjobs_production
  username: dreamjobs
  password: <%= ENV['DREAMJOBS_DATABASE_PASSWORD'] %>
